/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 boy.glb -T 
Files: boy.glb [14.66MB] > C:\Users\Sachin\Desktop\Portfolio\public\modals\boy-transformed.glb [1.38MB] (91%)
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations, useFBX } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function ContactBoy(props) {
  const group = React.useRef()
  const { scene } = useGLTF('/modals/boy-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { animations } = useFBX('/modals/greet.fbx')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    const sceneAction = actions?.Scene
    const firstAction = actions && Object.values(actions)[0]

    const toPlay = sceneAction ?? firstAction
    toPlay?.reset().play()

    return () => toPlay?.fadeOut?.(0.2)
  }, [actions])

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      // TWEAK THESE:
      position={[0, -3.7, 0]}     // x, y, z (move up/down with y)
      rotation={[-1.5, 0, 0]}  // rotate around y; try ±Math.PI/2, Math.PI
      scale={3.8}                 // overall size
    >
      <group name="Scene">
        <group name="Armature" scale={0.01}>
          <primitive object={nodes.Hips} />
        </group>
        <skinnedMesh
          name="char1"
          geometry={nodes.char1.geometry}
          material={materials.Material_1}
          skeleton={nodes.char1.skeleton}
          scale={0.01}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/modals/boy-transformed.glb')
