/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 boy.glb -T
Files: boy.glb [14.66MB] > C:\Users\Sachin\Desktop\Portfolio\public\modals\boy-transformed.glb [1.38MB] (91%)
*/

import React, { useEffect, useRef, useMemo } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations, useFBX } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { LoopOnce } from 'three'

export function HeroBoy(props) {
  const group = useRef()
  const { scene } = useGLTF('/modals/boy-transformed.glb')

  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)

  const { animations } = useFBX('/modals/hello.fbx')
  const { actions, names, mixer } = useAnimations(animations, group)

  // Gate: enable cursor-follow only after the intro animation finishes
  const followEnabledRef = useRef(false)

  useEffect(() => {
    const action = actions?.Scene ?? actions?.[names?.[0]]
    if (!action) return

    followEnabledRef.current = false

    // Play once
    action.reset()
    action.setLoop(LoopOnce, 1)
    action.clampWhenFinished = true
    action.fadeIn(0.2).play()

    const onFinished = (e) => {
      // Ensure it's OUR action that finished (not some other mixer action)
      if (e?.action !== action) return
      followEnabledRef.current = true
    }

    mixer?.addEventListener('finished', onFinished)

    return () => {
      mixer?.removeEventListener('finished', onFinished)
      action.fadeOut(0.2)
      action.stop()
    }
  }, [actions, names, mixer])

  // Cursor-follow (extracted from your previous file), but only after animation finishes
  useEffect(() => {
    const handleMouseMove = (event) => {
      if (!followEnabledRef.current) return

      const { innerWidth, innerHeight } = window

      // Normalize mouse position to -1..1 range (kept from your previous code)
      const x = (event.clientX / innerWidth) * 2 - 1
      const y = (event.clientY / innerHeight) * 2.8 - 1 + 0.9094936708860757

      // Get the head bone
      const head = group.current?.getObjectByName('Head')
      if (head) {
        // Rotate head left/right based on mouse X
        head.rotation.y = x * 0.5

        // Rotate head up/down based on mouse Y
        head.rotation.x = y * 0.55

        // Add slight tilt
        head.rotation.z = -x * 0.1
      }

      // Rotate body slightly based on mouse X position
      if (group.current) {
        group.current.rotation.y = x * 0.15
      }
    }

    window.addEventListener('mousemove', handleMouseMove)
    return () => window.removeEventListener('mousemove', handleMouseMove)
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      {/* Stable transform wrapper (adjust these 3 to fit your layout) */}
      <group
        name="BoyRoot"
        position={[-0.5, -0.2, 0]} // move right/down (tweak)
        rotation={[-1, 0, 0]} // face camera (tweak if needed)
        scale={1.2} // overall scale (tweak)
      >
        <group name="Scene">
          <group name="Armature" scale={0.01}>
            <primitive object={nodes.Hips} />
          </group>
          <skinnedMesh
            name="char1"
            geometry={nodes.char1.geometry}
            material={materials.Material_1}
            skeleton={nodes.char1.skeleton}
            scale={0.01}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/modals/boy-transformed.glb')
